name: Test & Build

on:
  push:
    branches:
    - master

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and test
      run: |
        npm install
        npm test
  build:
    needs: unit-tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.16.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install and build
      run: |
        npm install
        npm run build

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: 'Test & Build'
          channel: '#release-notifications'
          url: ${{ secrets.SLACK_WEBHOOK }}
          icon_emoji: green_apple
          username: palekhfest GitHub workflows
