name: Build & Test

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, test and build
      run: |
        npm install
        npm run build
        npm test

    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
          type: ${{ job.status }}
          job_name: 'Build & Test'
          channel: '#release-notifications'
          url: ${{ secrets.SLACK_WEBHOOK }}
          icon_emoji: green_apple
          username: palekhfest GitHub workflows
